export const defaultKotoba = [
    { id: 1, romaji: 'watashi', kana: 'わたし', kanji: '私', meaning: 'Saya', is_default: true },
    { id: 2, romaji: 'anata', kana: 'あなた', kanji: '', meaning: 'Kamu', is_default: true },
    { id: 3, romaji: 'ano hito', kana: 'あのひと', kanji: 'あの人', meaning: 'Orang itu (biasa)', is_default: true },
    { id: 4, romaji: 'ano kata', kana: 'あのかた', kanji: 'あの方', meaning: 'Orang itu (sopan)', is_default: true },
    { id: 5, romaji: 'san', kana: '～さん', kanji: '', meaning: 'Saudara, Tuan, Nyonya', is_default: true },
    { id: 6, romaji: 'chan', kana: '～ちゃん', kanji: '', meaning: 'Panggilan untuk anak perempuan', is_default: true },
    { id: 7, romaji: 'jin', kana: '～じん', kanji: '～人', meaning: 'Orang... (akhiran untuk warga negara)', is_default: true },
    { id: 8, romaji: 'sensei', kana: 'せんせい', kanji: '先生', meaning: 'Guru, dosen (tidak dipakai untuk kalangan sendiri)', is_default: true },
    { id: 9, romaji: 'kyoushi', kana: 'きょうし', kanji: '教師', meaning: 'Guru, dosen (dipakai untuk kalangan sendiri)', is_default: true },
    { id: 10, romaji: 'gakusei', kana: 'がくせい', kanji: '学生', meaning: 'Siswa, murid', is_default: true },
    { id: 11, romaji: 'kaishain', kana: 'かいしゃいん', kanji: '会社員', meaning: 'Pegawai perusahaan', is_default: true },
    { id: 12, romaji: 'shain', kana: 'しゃいん', kanji: '社員', meaning: 'Pegawai~', is_default: true },
    { id: 13, romaji: 'ginkouin', kana: 'ぎんこういん', kanji: '銀行員', meaning: 'Pegawai bank', is_default: true },
    { id: 14, romaji: 'isha', kana: 'いしゃ', kanji: '医者', meaning: 'Dokter', is_default: true },
    { id: 15, romaji: 'kenkyuusha', kana: 'けんきゅうしゃ', kanji: '研究者', meaning: 'Peneliti', is_default: true },
    { id: 16, romaji: 'daigaku', kana: 'だいがく', kanji: '大学', meaning: 'Universitas', is_default: true },
    { id: 17, romaji: 'byouin', kana: 'びょういん', kanji: '病院', meaning: 'Rumah sakit', is_default: true },
    { id: 18, romaji: 'dare', kana: 'だれ', kanji: '', meaning: 'Siapa (biasa)', is_default: true },
    { id: 19, romaji: 'donata', kana: 'どなた', kanji: '', meaning: 'Siapa (sopan)', is_default: true },
    { id: 20, romaji: 'sai', kana: '～さい', kanji: '～歳', meaning: 'Umur~', is_default: true },
    { id: 21, romaji: 'nan sai', kana: 'なんさい', kanji: '何歳', meaning: 'Umur berapa? (biasa)', is_default: true },
    { id: 22, romaji: 'oikutsu', kana: 'おいくつ', kanji: '', meaning: 'Umur berapa? (sopan)', is_default: true },
    { id: 23, romaji: 'hai', kana: 'はい', kanji: '', meaning: 'Iya', is_default: true },
    { id: 24, romaji: 'iie', kana: 'いいえ', kanji: '', meaning: 'Tidak', is_default: true },
    { id: 25, romaji: 'hajimemashite', kana: 'はじめまして', kanji: '', meaning: 'Perkenalkan', is_default: true },
    { id: 26, romaji: 'kara kimashita', kana: '～からきました', kanji: '～から来ました', meaning: 'Datang dari..', is_default: true },
    { id: 27, romaji: 'douzo yoroshiku onegaishimasu', kana: 'どうぞよろしくおねがいします', kanji: 'どうぞよろしくお願いします', meaning: 'Senang bertemu dengan anda', is_default: true },
    { id: 28, romaji: 'shitsurei desu ga', kana: 'しつれいですが', kanji: '失礼ですが', meaning: 'Permisi', is_default: true },
    { id: 29, romaji: 'onamae wa', kana: 'おなまえは', kanji: 'お名前は', meaning: 'Nama anda siapa?', is_default: true },
    { id: 30, romaji: 'amerika', kana: 'アメリカ', kanji: '', meaning: 'Amerika', is_default: true },
    { id: 31, romaji: 'igirisu', kana: 'イギリス', kanji: '', meaning: 'Inggris', is_default: true },
    { id: 32, romaji: 'indo', kana: 'インド', kanji: '', meaning: 'India', is_default: true },
    { id: 33, romaji: 'indoneshia', kana: 'インドネシア', kanji: '', meaning: 'Indonesia', is_default: true },
    { id: 34, romaji: 'kankoku', kana: 'かんこく', kanji: '韓国', meaning: 'Korea', is_default: true },
    { id: 35, romaji: 'chuugoku', kana: 'ちゅうごく', kanji: '中国', meaning: 'China', is_default: true },
    { id: 36, romaji: 'doitsu', kana: 'ドイツ', kanji: '', meaning: 'Jerman', is_default: true },
    { id: 37, romaji: 'nihon', kana: 'にほん', kanji: '日本', meaning: 'Jepang', is_default: true },
];

export const kanaSets = {
    hiragana: [
        ['あ', 'a'], ['い', 'i'], ['う', 'u'], ['え', 'e'], ['お', 'o'],
        ['か', 'ka'], ['き', 'ki'], ['く', 'ku'], ['け', 'ke'], ['こ', 'ko'],
        ['さ', 'sa'], ['し', 'shi'], ['す', 'su'], ['せ', 'se'], ['そ', 'so'],
        ['た', 'ta'], ['ち', 'chi'], ['つ', 'tsu'], ['て', 'te'], ['と', 'to'],
        ['な', 'na'], ['に', 'ni'], ['ぬ', 'nu'], ['ね', 'ne'], ['の', 'no'],
        ['は', 'ha'], ['ひ', 'hi'], ['ふ', 'fu'], ['へ', 'he'], ['ほ', 'ho'],
        ['ま', 'ma'], ['み', 'mi'], ['む', 'mu'], ['め', 'me'], ['も', 'mo'],
        ['や', 'ya'], ['ゆ', 'yu'], ['よ', 'yo'],
        ['ら', 'ra'], ['り', 'ri'], ['る', 'ru'], ['れ', 're'], ['ろ', 'ro'],
        ['わ', 'wa'], ['を', 'wo'], ['ん', 'n'],
    ],
    katakana: [
        ['ア', 'a'], ['イ', 'i'], ['ウ', 'u'], ['エ', 'e'], ['オ', 'o'],
        ['カ', 'ka'], ['キ', 'ki'], ['ク', 'ku'], ['ケ', 'ke'], ['コ', 'ko'],
        ['サ', 'sa'], ['シ', 'shi'], ['ス', 'su'], ['セ', 'se'], ['ソ', 'so'],
        ['タ', 'ta'], ['チ', 'chi'], ['ツ', 'tsu'], ['テ', 'te'], ['ト', 'to'],
        ['ナ', 'na'], ['ニ', 'ni'], ['ヌ', 'nu'], ['ネ', 'ne'], ['ノ', 'no'],
        ['ハ', 'ha'], ['ヒ', 'hi'], ['フ', 'fu'], ['ヘ', 'he'], ['ホ', 'ho'],
        ['マ', 'ma'], ['ミ', 'mi'], ['ム', 'mu'], ['メ', 'me'], ['モ', 'mo'],
        ['ヤ', 'ya'], ['ユ', 'yu'], ['ヨ', 'yo'],
        ['ラ', 'ra'], ['リ', 'ri'], ['ル', 'ru'], ['レ', 're'], ['ロ', 'ro'],
        ['ワ', 'wa'], ['ヲ', 'wo'], ['ン', 'n'],
    ],
};
